# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown

only: pulls

pulls:
  comment: >
    This repository does not accept pull requests.
    Please read the CONTRIBUTING document at https://github.com/kingfisher63/avm_juischeck for guidance.
